### ISSUE TITLE
TODO before open sourcing

### ISSUE THREAD

**Issue by Aciz** [etjump/etjump#464]
Stuff to do before open sourcing mod.

- [ ] Release 2.4.0
- [ ] Convert project to CMake  
  * [ ] Improve packing scripts (#385)
- [ ] Write proper code style guide
- [ ] Mod version handling for local builds
